export const COLORS = {
  paper: "#F7F2E9",
  ink: "#22201B",
  primary: "#F2994A",
  secondary: "#5B5FEF",
  mint: "#3FBF9F",
  sun: "#FFD166",
  pencil: "#8B8478",
  line: "#EAE3D3",
};

export const styles = {
  page: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    backgroundColor: COLORS.paper,
    fontFamily: "'Manrope', sans-serif",
    color: COLORS.ink,
    overflow: "hidden",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: "24px",
    padding: "15px 5px 15px 20px",
    borderBottom: `1.5px solid ${COLORS.ink}`,
    background: "#fff",
    flexShrink: 0,
    zIndex: 10,                      // ताकि नवबार हमेशा सबसे ऊपर तैरता रहे
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontFamily: "'Gochi Hand', cursive",
    fontSize: "26px",
    flexShrink: 0,
  },
  searchBox: {
    flex: 1,
    maxWidth: "420px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    border: `1.5px solid ${COLORS.ink}`,
    padding: "8px 14px",
    background: COLORS.paper,
  },
  searchInput: { border: "none", background: "transparent", outline: "none", fontSize: "14px", width: "100%" },
  navRight: { display: "flex", alignItems: "center", gap: "10px", marginLeft: "auto" },
  iconButton: {
    border: `1.5px solid ${COLORS.ink}`,
    background: "#fff",
    width: "36px",
    height: "36px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  avatar: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    background: COLORS.secondary,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Architects Daughter', cursive",
  },
  main: { 
    width: "100%",
    maxWidth: "820px", 
    margin: "0 auto", 
    padding: "0 24px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  greeting: {
    fontFamily: "'Gochi Hand', cursive",
    fontSize: "40px",
    margin: "20px 0 4px",           // मार्जिन थोड़ा कम किया ताकि ऊपर स्पेस परफेक्ट दिखे
    flexShrink: 0,
  },
  subtext: { 
    color: COLORS.pencil, 
    fontSize: "14.5px", 
    marginBottom: "28px",
    flexShrink: 0, 
  },
  pillRow: { 
    display: "flex", 
    gap: "10px", 
    flexWrap: "wrap", 
    marginBottom: "32px",
    flexShrink: 0, 
  },
  pill: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "#fff",
    border: `1.5px solid ${COLORS.ink}`,
    borderRadius: "999px",
    padding: "10px 18px",
    fontFamily: "'Architects Daughter', cursive",
    fontSize: "14px",
    cursor: "pointer",
  },
  tabRow: {
    display: "flex",
    gap: "6px",
    borderBottom: `1.5px solid ${COLORS.line}`,
    marginBottom: "6px",
    flexShrink: 0, 
  },
  tab: {
    background: "none",
    border: "none",
    padding: "10px 6px",
    marginRight: "18px",
    fontSize: "14px",
    color: COLORS.pencil,
    cursor: "pointer",
    borderBottom: "2.5px solid transparent",
  },
  tabActive: {
    color: COLORS.ink,
    fontWeight: 700,
    borderBottom: `2.5px solid ${COLORS.primary}`,
  },
  boardList: { 
    display: "flex", 
    flexDirection: "column",
    flex: 1,
    overflowY: "auto",
    paddingBottom: "40px",
    scrollbarWidth: "thin",          
    scrollbarColor: "rgba(34, 32, 27, 0.25) transparent",
  },
  boardRow: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    padding: "16px 6px",
    borderBottom: `1.5px solid ${COLORS.line}`,
  },
  boardSwatch: {
    width: "40px",
    height: "40px",
    borderRadius: "8px",
    flexShrink: 0,
  },
  boardInfo: { flex: 1 },
  boardTitle: { fontFamily: "'Architects Daughter', cursive", fontSize: "15.5px" },
  boardMeta: { fontSize: "12.5px", color: COLORS.pencil, marginTop: "2px" },
  moreButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: COLORS.pencil,
  },
};